//! ClaimResponse
//!
//! URL: http://hl7.org/fhir/StructureDefinition/ClaimResponse
//!
//! Version: 5.0.0
//!
//! ClaimResponse Resource: This resource provides the adjudication details from the processing of a Claim resource.
//!
//! FHIR: <https://build.fhir.org/>
//!
//! UML: <https://build.fhir.org/uml.html>

// Allow unused crate::r5::types as types;
#![allow(unused_imports)]

use crate::r5::types;
use ::serde::{Deserialize, Serialize};
use fhir_derive_macros::Validate;

/// This resource provides the adjudication details from the processing of a
/// Claim resource. It conveys the outcome of an insurer's or payer's processing
/// of a submitted claim, preauthorization, or predetermination, including
/// adjudicated amounts, notes, payment details, and any processing errors.
/// A ClaimResponse is typically returned in reply to a Claim request.
///
/// Administratively, a ClaimResponse is generated by the adjudicating payer
/// (insurer) after it evaluates a submitted `Claim` against coverage rules,
/// benefit limits, and contracted pricing. Depending on the value of `use`,
/// the response may represent the final adjudication of a `claim`, or an
/// informational outcome for a `preauthorization` or `predetermination`
/// request submitted in advance of service delivery. The resource captures
/// line-item level adjudication (via `item` and its nested `detail` and
/// `sub_detail` structures), insurer-added items not present on the original
/// claim (`add_item`), aggregate `total` amounts, `payment` information, and
/// any `error` entries describing why processing could not complete
/// successfully. Systems typically correlate a ClaimResponse back to its
/// originating claim using the `request` reference, and to the subject of
/// care using the `patient` reference.
///
/// Related resources: see also [`CodeableConcept`](crate::r5::types::CodeableConcept)
/// for coded fields such as `status` categories and adjudication `category`
/// values, and `Claim`, `Coverage`, and `Patient` for the request, insurance,
/// and subject resources this ClaimResponse relates to.
///
/// # Examples
///
/// ```
/// use fhir::r5::resources::claim_response::ClaimResponse;
///
/// let value = ClaimResponse::default();
/// let json = ::serde_json::to_value(&value).unwrap();
/// let back: ClaimResponse = ::serde_json::from_value(json).unwrap();
/// assert_eq!(value, back);
/// ```
#[serde_with::skip_serializing_none]
#[derive(Debug, Default, Clone, Serialize, Deserialize, PartialEq, Eq, Validate)]
#[serde(rename_all = "camelCase")]
pub struct ClaimResponse {
    /// Logical id of this artifact
    pub id: Option<types::String>,

    /// Metadata about the resource
    pub meta: Option<types::Meta>,

    /// A set of rules under which this content was created
    pub implicit_rules: Option<types::Uri>,
    /// Primitive extension sibling for [`implicit_rules`](Self::implicit_rules) (FHIR `_implicitRules`).
    #[serde(rename = "_implicitRules")]
    pub implicit_rules_ext: Option<types::Element>,

    /// Language of the resource content
    pub language: Option<types::Code>,
    /// Primitive extension sibling for [`language`](Self::language) (FHIR `_language`).
    #[serde(rename = "_language")]
    pub language_ext: Option<types::Element>,

    /// Text summary of the resource, for human interpretation
    pub text: Option<types::Narrative>,

    /// Contained, inline Resources
    pub contained: Option<Vec<::serde_json::Value>>,

    /// Additional content defined by implementations
    pub extension: Option<Vec<types::Extension>>,

    /// Extensions that cannot be ignored
    pub modifier_extension: Option<Vec<types::Extension>>,

    /// Business Identifier for a claim response
    pub identifier: Option<Vec<types::Identifier>>,

    /// Number for tracking
    pub trace_number: Option<Vec<types::Identifier>>,

    /// The status of the resource instance itself: active | cancelled | draft | entered-in-error.
    pub status: crate::r5::coded::Coded<crate::r5::codes::FmStatus>,
    /// Primitive extension sibling for [`status`](Self::status) (FHIR `_status`).
    #[serde(rename = "_status")]
    pub status_ext: Option<types::Element>,

    /// The category of claim, such as institutional, oral, pharmacy, professional, or vision.
    pub r#type: types::CodeableConcept,

    /// More granular claim type
    pub sub_type: Option<types::CodeableConcept>,

    /// Indicates whether this response adjudicates a claim, preauthorization, or predetermination: claim | preauthorization | predetermination.
    pub r#use: crate::r5::coded::Coded<crate::r5::codes::ClaimUse>,
    /// Primitive extension sibling for [`use`](Self::r#use) (FHIR `_use`).
    #[serde(rename = "_use")]
    pub use_ext: Option<types::Element>,

    /// Reference to the [`Patient`](crate::r5::resources::patient::Patient) who is the subject of the claim being adjudicated.
    pub patient: types::Reference,

    /// The date and time this ClaimResponse was created by the insurer.
    pub created: types::DateTime,
    /// Primitive extension sibling for [`created`](Self::created) (FHIR `_created`).
    #[serde(rename = "_created")]
    pub created_ext: Option<types::Element>,

    /// Party responsible for reimbursement
    pub insurer: Option<types::Reference>,

    /// Party responsible for the claim
    pub requestor: Option<types::Reference>,

    /// Reference to the `Claim` resource that triggered this adjudication.
    pub request: Option<types::Reference>,

    /// The high-level processing outcome of the adjudication: queued | complete | error | partial.
    pub outcome: crate::r5::coded::Coded<crate::r5::codes::ClaimOutcome>,
    /// Primitive extension sibling for [`outcome`](Self::outcome) (FHIR `_outcome`).
    #[serde(rename = "_outcome")]
    pub outcome_ext: Option<types::Element>,

    /// Result of the adjudication
    pub decision: Option<types::CodeableConcept>,

    /// Disposition Message
    pub disposition: Option<types::String>,
    /// Primitive extension sibling for [`disposition`](Self::disposition) (FHIR `_disposition`).
    #[serde(rename = "_disposition")]
    pub disposition_ext: Option<types::Element>,

    /// Preauthorization reference
    pub pre_auth_ref: Option<types::String>,
    /// Primitive extension sibling for [`pre_auth_ref`](Self::pre_auth_ref) (FHIR `_preAuthRef`).
    #[serde(rename = "_preAuthRef")]
    pub pre_auth_ref_ext: Option<types::Element>,

    /// Preauthorization reference effective period
    pub pre_auth_period: Option<types::Period>,

    /// Event information
    pub event: Option<Vec<ClaimResponseEvent>>,

    /// Party to be paid any benefits payable
    pub payee_type: Option<types::CodeableConcept>,

    /// Encounters associated with the listed treatments
    pub encounter: Option<Vec<types::Reference>>,

    /// Package billing code
    pub diagnosis_related_group: Option<types::CodeableConcept>,

    /// Adjudication for claim line items
    pub item: Option<Vec<ClaimResponseItem>>,

    /// Insurer added line items
    pub add_item: Option<Vec<ClaimResponseAddItem>>,

    /// Header-level adjudication
    pub adjudication: Option<Vec<ClaimResponseItemAdjudication>>,

    /// Aggregate adjudication totals by category, such as submitted, benefit, and copay amounts.
    pub total: Option<Vec<ClaimResponseTotal>>,

    /// Details of any payment issued to the payee for this claim.
    pub payment: Option<ClaimResponsePayment>,

    /// Funds reserved status
    pub funds_reserve: Option<types::CodeableConcept>,

    /// Printed form identifier
    pub form_code: Option<types::CodeableConcept>,

    /// Printed reference or actual form
    pub form: Option<types::Attachment>,

    /// Note concerning adjudication
    pub process_note: Option<Vec<ClaimResponseProcessNote>>,

    /// Request for additional information
    pub communication_request: Option<Vec<types::Reference>>,

    /// Patient insurance information
    pub insurance: Option<Vec<ClaimResponseInsurance>>,

    /// Processing errors
    pub error: Option<Vec<ClaimResponseError>>,
}

/// Event information for the ClaimResponse.
#[serde_with::skip_serializing_none]
#[derive(Debug, Default, Clone, Serialize, Deserialize, PartialEq, Eq, Validate)]
#[serde(rename_all = "camelCase")]
pub struct ClaimResponseEvent {
    /// Unique id for inter-element referencing
    pub id: Option<types::String>,

    /// Additional content defined by implementations
    pub extension: Option<Vec<types::Extension>>,

    /// Extensions that cannot be ignored even if unrecognized
    pub modifier_extension: Option<Vec<types::Extension>>,

    /// Specific event
    pub r#type: types::CodeableConcept,

    /// The `ClaimResponse.event.when[x]` choice element (0..1); see [`ClaimResponseEventWhen`].
    #[serde(flatten)]
    pub when: Option<ClaimResponseEventWhen>,
}

/// Adjudication for claim line items.
#[serde_with::skip_serializing_none]
#[derive(Debug, Default, Clone, Serialize, Deserialize, PartialEq, Eq, Validate)]
#[serde(rename_all = "camelCase")]
pub struct ClaimResponseItem {
    /// Unique id for inter-element referencing
    pub id: Option<types::String>,

    /// Additional content defined by implementations
    pub extension: Option<Vec<types::Extension>>,

    /// Extensions that cannot be ignored even if unrecognized
    pub modifier_extension: Option<Vec<types::Extension>>,

    /// Claim item instance identifier
    pub item_sequence: types::PositiveInt,
    /// Primitive extension sibling for [`item_sequence`](Self::item_sequence) (FHIR `_itemSequence`).
    #[serde(rename = "_itemSequence")]
    pub item_sequence_ext: Option<types::Element>,

    /// Number for tracking
    pub trace_number: Option<Vec<types::Identifier>>,

    /// Applicable note numbers
    pub note_number: Option<Vec<types::PositiveInt>>,
    /// Primitive extension sibling for [`note_number`](Self::note_number) (FHIR `_noteNumber`).
    #[serde(rename = "_noteNumber")]
    pub note_number_ext: Option<Vec<Option<types::Element>>>,

    /// Adjudication results
    pub review_outcome: Option<ClaimResponseItemReviewOutcome>,

    /// Adjudication details
    pub adjudication: Option<Vec<ClaimResponseItemAdjudication>>,

    /// Adjudication for claim details
    pub detail: Option<Vec<ClaimResponseItemDetail>>,
}

/// Adjudication results for a claim item.
#[serde_with::skip_serializing_none]
#[derive(Debug, Default, Clone, Serialize, Deserialize, PartialEq, Eq, Validate)]
#[serde(rename_all = "camelCase")]
pub struct ClaimResponseItemReviewOutcome {
    /// Unique id for inter-element referencing
    pub id: Option<types::String>,

    /// Additional content defined by implementations
    pub extension: Option<Vec<types::Extension>>,

    /// Extensions that cannot be ignored even if unrecognized
    pub modifier_extension: Option<Vec<types::Extension>>,

    /// Result of the adjudication
    pub decision: Option<types::CodeableConcept>,

    /// Reason for result of the adjudication
    pub reason: Option<Vec<types::CodeableConcept>>,

    /// Preauthorization reference
    pub pre_auth_ref: Option<types::String>,
    /// Primitive extension sibling for [`pre_auth_ref`](Self::pre_auth_ref) (FHIR `_preAuthRef`).
    #[serde(rename = "_preAuthRef")]
    pub pre_auth_ref_ext: Option<types::Element>,

    /// Preauthorization reference effective period
    pub pre_auth_period: Option<types::Period>,
}

/// Adjudication details for a claim item.
#[serde_with::skip_serializing_none]
#[derive(Debug, Default, Clone, Serialize, Deserialize, PartialEq, Eq, Validate)]
#[serde(rename_all = "camelCase")]
pub struct ClaimResponseItemAdjudication {
    /// Unique id for inter-element referencing
    pub id: Option<types::String>,

    /// Additional content defined by implementations
    pub extension: Option<Vec<types::Extension>>,

    /// Extensions that cannot be ignored even if unrecognized
    pub modifier_extension: Option<Vec<types::Extension>>,

    /// Type of adjudication information
    pub category: types::CodeableConcept,

    /// Explanation of adjudication outcome
    pub reason: Option<types::CodeableConcept>,

    /// Monetary amount
    pub amount: Option<types::Money>,

    /// Non-monetary value
    pub quantity: Option<types::Quantity>,
}

/// Adjudication for claim details.
#[serde_with::skip_serializing_none]
#[derive(Debug, Default, Clone, Serialize, Deserialize, PartialEq, Eq, Validate)]
#[serde(rename_all = "camelCase")]
pub struct ClaimResponseItemDetail {
    /// Unique id for inter-element referencing
    pub id: Option<types::String>,

    /// Additional content defined by implementations
    pub extension: Option<Vec<types::Extension>>,

    /// Extensions that cannot be ignored even if unrecognized
    pub modifier_extension: Option<Vec<types::Extension>>,

    /// Claim detail instance identifier
    pub detail_sequence: types::PositiveInt,
    /// Primitive extension sibling for [`detail_sequence`](Self::detail_sequence) (FHIR `_detailSequence`).
    #[serde(rename = "_detailSequence")]
    pub detail_sequence_ext: Option<types::Element>,

    /// Number for tracking
    pub trace_number: Option<Vec<types::Identifier>>,

    /// Applicable note numbers
    pub note_number: Option<Vec<types::PositiveInt>>,
    /// Primitive extension sibling for [`note_number`](Self::note_number) (FHIR `_noteNumber`).
    #[serde(rename = "_noteNumber")]
    pub note_number_ext: Option<Vec<Option<types::Element>>>,

    /// Detail level adjudication results
    pub review_outcome: Option<ClaimResponseItemReviewOutcome>,

    /// Detail level adjudication details
    pub adjudication: Option<Vec<ClaimResponseItemAdjudication>>,

    /// Adjudication for claim sub-details
    pub sub_detail: Option<Vec<ClaimResponseItemDetailSubDetail>>,
}

/// Adjudication for claim sub-details.
#[serde_with::skip_serializing_none]
#[derive(Debug, Default, Clone, Serialize, Deserialize, PartialEq, Eq, Validate)]
#[serde(rename_all = "camelCase")]
pub struct ClaimResponseItemDetailSubDetail {
    /// Unique id for inter-element referencing
    pub id: Option<types::String>,

    /// Additional content defined by implementations
    pub extension: Option<Vec<types::Extension>>,

    /// Extensions that cannot be ignored even if unrecognized
    pub modifier_extension: Option<Vec<types::Extension>>,

    /// Claim sub-detail instance identifier
    pub sub_detail_sequence: types::PositiveInt,
    /// Primitive extension sibling for [`sub_detail_sequence`](Self::sub_detail_sequence) (FHIR `_subDetailSequence`).
    #[serde(rename = "_subDetailSequence")]
    pub sub_detail_sequence_ext: Option<types::Element>,

    /// Number for tracking
    pub trace_number: Option<Vec<types::Identifier>>,

    /// Applicable note numbers
    pub note_number: Option<Vec<types::PositiveInt>>,
    /// Primitive extension sibling for [`note_number`](Self::note_number) (FHIR `_noteNumber`).
    #[serde(rename = "_noteNumber")]
    pub note_number_ext: Option<Vec<Option<types::Element>>>,

    /// Subdetail level adjudication results
    pub review_outcome: Option<ClaimResponseItemReviewOutcome>,

    /// Subdetail level adjudication details
    pub adjudication: Option<Vec<ClaimResponseItemAdjudication>>,
}

/// Insurer added line items.
#[serde_with::skip_serializing_none]
#[derive(Debug, Default, Clone, Serialize, Deserialize, PartialEq, Eq, Validate)]
#[serde(rename_all = "camelCase")]
pub struct ClaimResponseAddItem {
    /// Unique id for inter-element referencing
    pub id: Option<types::String>,

    /// Additional content defined by implementations
    pub extension: Option<Vec<types::Extension>>,

    /// Extensions that cannot be ignored even if unrecognized
    pub modifier_extension: Option<Vec<types::Extension>>,

    /// Item sequence number
    pub item_sequence: Option<Vec<types::PositiveInt>>,
    /// Primitive extension sibling for [`item_sequence`](Self::item_sequence) (FHIR `_itemSequence`).
    #[serde(rename = "_itemSequence")]
    pub item_sequence_ext: Option<Vec<Option<types::Element>>>,

    /// Detail sequence number
    pub detail_sequence: Option<Vec<types::PositiveInt>>,
    /// Primitive extension sibling for [`detail_sequence`](Self::detail_sequence) (FHIR `_detailSequence`).
    #[serde(rename = "_detailSequence")]
    pub detail_sequence_ext: Option<Vec<Option<types::Element>>>,

    /// Subdetail sequence number
    pub subdetail_sequence: Option<Vec<types::PositiveInt>>,
    /// Primitive extension sibling for [`subdetail_sequence`](Self::subdetail_sequence) (FHIR `_subdetailSequence`).
    #[serde(rename = "_subdetailSequence")]
    pub subdetail_sequence_ext: Option<Vec<Option<types::Element>>>,

    /// Number for tracking
    pub trace_number: Option<Vec<types::Identifier>>,

    /// Authorized providers
    pub provider: Option<Vec<types::Reference>>,

    /// Revenue or cost center code
    pub revenue: Option<types::CodeableConcept>,

    /// Billing, service, product, or drug code
    pub product_or_service: Option<types::CodeableConcept>,

    /// End of a range of codes
    pub product_or_service_end: Option<types::CodeableConcept>,

    /// Request or Referral for Service
    pub request: Option<Vec<types::Reference>>,

    /// Service/Product billing modifiers
    pub modifier: Option<Vec<types::CodeableConcept>>,

    /// Program the product or service is provided under
    pub program_code: Option<Vec<types::CodeableConcept>>,

    /// The `ClaimResponse.addItem.serviced[x]` choice element (0..1); see [`ClaimResponseAddItemServiced`].
    #[serde(flatten)]
    pub serviced: Option<ClaimResponseAddItemServiced>,

    /// The `ClaimResponse.addItem.location[x]` choice element (0..1); see [`ClaimResponseAddItemLocation`].
    #[serde(flatten)]
    pub location: Option<ClaimResponseAddItemLocation>,

    /// Count of products or services
    pub quantity: Option<types::Quantity>,

    /// Fee, charge or cost per item
    pub unit_price: Option<types::Money>,

    /// Price scaling factor
    pub factor: Option<types::Decimal>,
    /// Primitive extension sibling for [`factor`](Self::factor) (FHIR `_factor`).
    #[serde(rename = "_factor")]
    pub factor_ext: Option<types::Element>,

    /// Total tax
    pub tax: Option<types::Money>,

    /// Total item cost
    pub net: Option<types::Money>,

    /// Anatomical location
    pub body_site: Option<Vec<ClaimResponseAddItemBodySite>>,

    /// Applicable note numbers
    pub note_number: Option<Vec<types::PositiveInt>>,
    /// Primitive extension sibling for [`note_number`](Self::note_number) (FHIR `_noteNumber`).
    #[serde(rename = "_noteNumber")]
    pub note_number_ext: Option<Vec<Option<types::Element>>>,

    /// Added items adjudication results
    pub review_outcome: Option<ClaimResponseItemReviewOutcome>,

    /// Added items adjudication
    pub adjudication: Option<Vec<ClaimResponseItemAdjudication>>,

    /// Insurer added line details
    pub detail: Option<Vec<ClaimResponseAddItemDetail>>,
}

/// Anatomical location for an insurer added line item.
#[serde_with::skip_serializing_none]
#[derive(Debug, Clone, Serialize, Deserialize, PartialEq, Eq, Validate)]
#[serde(rename_all = "camelCase")]
pub struct ClaimResponseAddItemBodySite {
    /// Unique id for inter-element referencing
    pub id: Option<types::String>,

    /// Additional content defined by implementations
    pub extension: Option<Vec<types::Extension>>,

    /// Extensions that cannot be ignored even if unrecognized
    pub modifier_extension: Option<Vec<types::Extension>>,

    /// Location
    pub site: vec1::Vec1<types::CodeableReference>,

    /// Sub-location
    pub sub_site: Option<Vec<types::CodeableConcept>>,
}

/// Insurer added line details.
#[serde_with::skip_serializing_none]
#[derive(Debug, Default, Clone, Serialize, Deserialize, PartialEq, Eq, Validate)]
#[serde(rename_all = "camelCase")]
pub struct ClaimResponseAddItemDetail {
    /// Unique id for inter-element referencing
    pub id: Option<types::String>,

    /// Additional content defined by implementations
    pub extension: Option<Vec<types::Extension>>,

    /// Extensions that cannot be ignored even if unrecognized
    pub modifier_extension: Option<Vec<types::Extension>>,

    /// Number for tracking
    pub trace_number: Option<Vec<types::Identifier>>,

    /// Revenue or cost center code
    pub revenue: Option<types::CodeableConcept>,

    /// Billing, service, product, or drug code
    pub product_or_service: Option<types::CodeableConcept>,

    /// End of a range of codes
    pub product_or_service_end: Option<types::CodeableConcept>,

    /// Service/Product billing modifiers
    pub modifier: Option<Vec<types::CodeableConcept>>,

    /// Count of products or services
    pub quantity: Option<types::Quantity>,

    /// Fee, charge or cost per item
    pub unit_price: Option<types::Money>,

    /// Price scaling factor
    pub factor: Option<types::Decimal>,
    /// Primitive extension sibling for [`factor`](Self::factor) (FHIR `_factor`).
    #[serde(rename = "_factor")]
    pub factor_ext: Option<types::Element>,

    /// Total tax
    pub tax: Option<types::Money>,

    /// Total item cost
    pub net: Option<types::Money>,

    /// Applicable note numbers
    pub note_number: Option<Vec<types::PositiveInt>>,
    /// Primitive extension sibling for [`note_number`](Self::note_number) (FHIR `_noteNumber`).
    #[serde(rename = "_noteNumber")]
    pub note_number_ext: Option<Vec<Option<types::Element>>>,

    /// Added items detail level adjudication results
    pub review_outcome: Option<ClaimResponseItemReviewOutcome>,

    /// Added items detail adjudication
    pub adjudication: Option<Vec<ClaimResponseItemAdjudication>>,

    /// Insurer added line items
    pub sub_detail: Option<Vec<ClaimResponseAddItemDetailSubDetail>>,
}

/// Insurer added line sub-details.
#[serde_with::skip_serializing_none]
#[derive(Debug, Default, Clone, Serialize, Deserialize, PartialEq, Eq, Validate)]
#[serde(rename_all = "camelCase")]
pub struct ClaimResponseAddItemDetailSubDetail {
    /// Unique id for inter-element referencing
    pub id: Option<types::String>,

    /// Additional content defined by implementations
    pub extension: Option<Vec<types::Extension>>,

    /// Extensions that cannot be ignored even if unrecognized
    pub modifier_extension: Option<Vec<types::Extension>>,

    /// Number for tracking
    pub trace_number: Option<Vec<types::Identifier>>,

    /// Revenue or cost center code
    pub revenue: Option<types::CodeableConcept>,

    /// Billing, service, product, or drug code
    pub product_or_service: Option<types::CodeableConcept>,

    /// End of a range of codes
    pub product_or_service_end: Option<types::CodeableConcept>,

    /// Service/Product billing modifiers
    pub modifier: Option<Vec<types::CodeableConcept>>,

    /// Count of products or services
    pub quantity: Option<types::Quantity>,

    /// Fee, charge or cost per item
    pub unit_price: Option<types::Money>,

    /// Price scaling factor
    pub factor: Option<types::Decimal>,
    /// Primitive extension sibling for [`factor`](Self::factor) (FHIR `_factor`).
    #[serde(rename = "_factor")]
    pub factor_ext: Option<types::Element>,

    /// Total tax
    pub tax: Option<types::Money>,

    /// Total item cost
    pub net: Option<types::Money>,

    /// Applicable note numbers
    pub note_number: Option<Vec<types::PositiveInt>>,
    /// Primitive extension sibling for [`note_number`](Self::note_number) (FHIR `_noteNumber`).
    #[serde(rename = "_noteNumber")]
    pub note_number_ext: Option<Vec<Option<types::Element>>>,

    /// Added items subdetail level adjudication results
    pub review_outcome: Option<ClaimResponseItemReviewOutcome>,

    /// Added items subdetail adjudication
    pub adjudication: Option<Vec<ClaimResponseItemAdjudication>>,
}

/// Adjudication totals.
#[serde_with::skip_serializing_none]
#[derive(Debug, Default, Clone, Serialize, Deserialize, PartialEq, Eq, Validate)]
#[serde(rename_all = "camelCase")]
pub struct ClaimResponseTotal {
    /// Unique id for inter-element referencing
    pub id: Option<types::String>,

    /// Additional content defined by implementations
    pub extension: Option<Vec<types::Extension>>,

    /// Extensions that cannot be ignored even if unrecognized
    pub modifier_extension: Option<Vec<types::Extension>>,

    /// Type of adjudication information
    pub category: types::CodeableConcept,

    /// Financial total for the category
    pub amount: types::Money,
}

/// Payment Details.
#[serde_with::skip_serializing_none]
#[derive(Debug, Default, Clone, Serialize, Deserialize, PartialEq, Eq, Validate)]
#[serde(rename_all = "camelCase")]
pub struct ClaimResponsePayment {
    /// Unique id for inter-element referencing
    pub id: Option<types::String>,

    /// Additional content defined by implementations
    pub extension: Option<Vec<types::Extension>>,

    /// Extensions that cannot be ignored even if unrecognized
    pub modifier_extension: Option<Vec<types::Extension>>,

    /// Partial or complete payment
    pub r#type: types::CodeableConcept,

    /// Payment adjustment for non-claim issues
    pub adjustment: Option<types::Money>,

    /// Explanation for the adjustment
    pub adjustment_reason: Option<types::CodeableConcept>,

    /// Expected date of payment
    pub date: Option<types::Date>,
    /// Primitive extension sibling for [`date`](Self::date) (FHIR `_date`).
    #[serde(rename = "_date")]
    pub date_ext: Option<types::Element>,

    /// Payable amount after adjustment
    pub amount: types::Money,

    /// Business identifier for the payment
    pub identifier: Option<types::Identifier>,
}

/// Note concerning adjudication.
#[serde_with::skip_serializing_none]
#[derive(Debug, Default, Clone, Serialize, Deserialize, PartialEq, Eq, Validate)]
#[serde(rename_all = "camelCase")]
pub struct ClaimResponseProcessNote {
    /// Unique id for inter-element referencing
    pub id: Option<types::String>,

    /// Additional content defined by implementations
    pub extension: Option<Vec<types::Extension>>,

    /// Extensions that cannot be ignored even if unrecognized
    pub modifier_extension: Option<Vec<types::Extension>>,

    /// Note instance identifier
    pub number: Option<types::PositiveInt>,
    /// Primitive extension sibling for [`number`](Self::number) (FHIR `_number`).
    #[serde(rename = "_number")]
    pub number_ext: Option<types::Element>,

    /// Note purpose
    pub r#type: Option<types::CodeableConcept>,

    /// Note explanatory text
    pub text: types::String,
    /// Primitive extension sibling for [`text`](Self::text) (FHIR `_text`).
    #[serde(rename = "_text")]
    pub text_ext: Option<types::Element>,

    /// Language of the text
    pub language: Option<types::CodeableConcept>,
}

/// Patient insurance information.
#[serde_with::skip_serializing_none]
#[derive(Debug, Default, Clone, Serialize, Deserialize, PartialEq, Eq, Validate)]
#[serde(rename_all = "camelCase")]
pub struct ClaimResponseInsurance {
    /// Unique id for inter-element referencing
    pub id: Option<types::String>,

    /// Additional content defined by implementations
    pub extension: Option<Vec<types::Extension>>,

    /// Extensions that cannot be ignored even if unrecognized
    pub modifier_extension: Option<Vec<types::Extension>>,

    /// Insurance instance identifier
    pub sequence: types::PositiveInt,
    /// Primitive extension sibling for [`sequence`](Self::sequence) (FHIR `_sequence`).
    #[serde(rename = "_sequence")]
    pub sequence_ext: Option<types::Element>,

    /// Coverage to be used for adjudication
    pub focal: types::Boolean,
    /// Primitive extension sibling for [`focal`](Self::focal) (FHIR `_focal`).
    #[serde(rename = "_focal")]
    pub focal_ext: Option<types::Element>,

    /// Insurance information
    pub coverage: types::Reference,

    /// Additional provider contract number
    pub business_arrangement: Option<types::String>,
    /// Primitive extension sibling for [`business_arrangement`](Self::business_arrangement) (FHIR `_businessArrangement`).
    #[serde(rename = "_businessArrangement")]
    pub business_arrangement_ext: Option<types::Element>,

    /// Adjudication results
    pub claim_response: Option<types::Reference>,
}

/// Processing errors.
#[serde_with::skip_serializing_none]
#[derive(Debug, Default, Clone, Serialize, Deserialize, PartialEq, Eq, Validate)]
#[serde(rename_all = "camelCase")]
pub struct ClaimResponseError {
    /// Unique id for inter-element referencing
    pub id: Option<types::String>,

    /// Additional content defined by implementations
    pub extension: Option<Vec<types::Extension>>,

    /// Extensions that cannot be ignored even if unrecognized
    pub modifier_extension: Option<Vec<types::Extension>>,

    /// Item sequence number
    pub item_sequence: Option<types::PositiveInt>,
    /// Primitive extension sibling for [`item_sequence`](Self::item_sequence) (FHIR `_itemSequence`).
    #[serde(rename = "_itemSequence")]
    pub item_sequence_ext: Option<types::Element>,

    /// Detail sequence number
    pub detail_sequence: Option<types::PositiveInt>,
    /// Primitive extension sibling for [`detail_sequence`](Self::detail_sequence) (FHIR `_detailSequence`).
    #[serde(rename = "_detailSequence")]
    pub detail_sequence_ext: Option<types::Element>,

    /// Subdetail sequence number
    pub sub_detail_sequence: Option<types::PositiveInt>,
    /// Primitive extension sibling for [`sub_detail_sequence`](Self::sub_detail_sequence) (FHIR `_subDetailSequence`).
    #[serde(rename = "_subDetailSequence")]
    pub sub_detail_sequence_ext: Option<types::Element>,

    /// Error code detailing processing issues
    pub code: types::CodeableConcept,

    /// FHIRPath of element(s) related to issue
    pub expression: Option<Vec<types::String>>,
    /// Primitive extension sibling for [`expression`](Self::expression) (FHIR `_expression`).
    #[serde(rename = "_expression")]
    pub expression_ext: Option<Vec<Option<types::Element>>>,
}

#[cfg(test)]
mod tests {
    use super::*;
    type T = ClaimResponse;

    #[test]
    fn test_default() {
        let _ = T::default();
    }

    #[test]
    fn test_serde_round_trip() {
        let value = T::default();
        let json = ::serde_json::to_value(&value).expect("to_value");
        let back: T = ::serde_json::from_value(json).expect("from_value");
        assert_eq!(value, back);
    }
}
/// The `ClaimResponse.addItem.location[x]` choice element (see spec/11-choice-types.md).
#[derive(Debug, Clone, PartialEq, Eq, fhir_derive_macros::FhirChoice, Validate)]
#[allow(clippy::large_enum_variant)]
pub enum ClaimResponseAddItemLocation {
    /// `locationCodeableConcept` variant.
    #[fhir("locationCodeableConcept")]
    CodeableConcept(Box<types::CodeableConcept>),
    /// `locationAddress` variant.
    #[fhir("locationAddress")]
    Address(Box<types::Address>),
    /// `locationReference` variant.
    #[fhir("locationReference")]
    Reference(Box<types::Reference>),
}

/// The `ClaimResponse.addItem.serviced[x]` choice element (see spec/11-choice-types.md).
#[derive(Debug, Clone, PartialEq, Eq, fhir_derive_macros::FhirChoice, Validate)]
#[allow(clippy::large_enum_variant)]
pub enum ClaimResponseAddItemServiced {
    /// `servicedDate` variant.
    #[fhir("servicedDate")]
    Date(crate::r5::choice::Primitive<types::Date>),
    /// `servicedPeriod` variant.
    #[fhir("servicedPeriod")]
    Period(Box<types::Period>),
}

/// The `ClaimResponse.event.when[x]` choice element (see spec/11-choice-types.md).
#[derive(Debug, Clone, PartialEq, Eq, fhir_derive_macros::FhirChoice, Validate)]
#[allow(clippy::large_enum_variant)]
pub enum ClaimResponseEventWhen {
    /// `whenDateTime` variant.
    #[fhir("whenDateTime")]
    DateTime(crate::r5::choice::Primitive<types::DateTime>),
    /// `whenPeriod` variant.
    #[fhir("whenPeriod")]
    Period(Box<types::Period>),
}